### ISSUE TITLE
Why reboot host?

### ISSUE THREAD

**Issue by december1981** [bkuhl/redis-overcommit-on-host#1]
In the Readme, the last step in "How to use" is to reboot host. As I understand it, when a value in `/proc/sys/vm` is modified manually (without also updating `/etc/sysctl.conf`), the change doesn't survive a reboot? It seems like a pointless step anyway -to reboot the host, then presumably restart the containers again- ?

**Comment by rmcsharry** [comment]
@december1981 I am wondering the exact same thing.

Also it would be nice if the 'How to Use' was expanded as it's not entirely clear how I can use this with docker-compose.

**Comment by JorgenVatle** [comment]
@rmcsharry I've gone ahead and added an example for docker-compose in my pull request. (#2)

Here's the fork for reference;
https://github.com/JorgenVatle/redis-overcommit-on-host
Do make sure to replace the Git URIs with the fork's as some changes have been made to the repository to add execute permissions to the `run.sh` script.

Hope this helps. 👍

**Comment by bkuhl** [comment]
Honestly I don't recall why I had that step in there.  Jorgen revisited this and made some great contributions and removed that from the docs.  I'll consider this resolved.
